baseURL = "http://example.org/"
languageCode = "ru-ru"
theme = "two-brothers-theme"

[taxonomies]
  category = "category"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    parent = "pages"
    identifier = "О нас"
    name = "О нас"
    url = "/about-us/"
    weight = 2
  [[menu.main]]
    parent = "pages"
    identifier = "Оплата и доставка"
    name = "Оплата и доставка"
    url = "/delivery-and-payment/"
    weight = 3
  [[menu.main]]
    parent = "pages"
    name = "Контакты"
    url = "/contacts/"
  [[menu.main]]
    parent = "pages"
    name = "Error 404"
    url = "/404.html/"

  [[menu.aside]]
    identifier = "Рюкзаки"
    name = "bags"
    url = "/bags"
    weight = 1
  [[menu.aside]]
    parent = "pages"
    identifier = "Сумки"
    name = "Сумки"
    url = "/bags2/"
    weight = 2
  [[menu.aside]]
    parent = "pages"
    identifier = "Аксессуары"
    name = "Аксессуары"
    url = "/accessorize/"
    weight = 3

[params]
  title = ""
