baseURL = "http://example.org/"
languageCode = "ru-ru"
[[menu.aside]]
name = "Главная"
url = "/"
weight = 1
[[menu.aside]]
identifier = "Спорт"
name = "Спорт"
url = "/categories/sport/"
weight = 4
[[menu.aside]]
identifier = "Кэжуал"
name = "Кэжуал"
url = "/categories/casual/"
weight = 3
[[menu.aside]]
identifier = "Бизнес"
name = "Бизнес"
url = "/categories/business/"
weight = 2
[[menu.main]]
name = "Контакты"
url = "/contacts/"
weight = 3
[[menu.main]]
identifier = "Оплата и доставка"
name = "Оплата и доставка"
url = "/delivery-and-payment/"
weight = 2
[[menu.main]]
name = "О нас"
url = "/about/"
weight = 1
[params]
logo = "/images/logo.svg"
title = ""
[taxonomies]
  sport = "sport"
  casual = "casual"
  business = "business"

